SistemaAcademia/Models/ErrorViewModel.cs
namespace SistemaAcademia.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaAcademia/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace SistemaAcademia.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage= "Informe o login do usuário")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Informe a senha do usuário")]
        public string Senha { get; set; }

    }
}

SistemaAcademia/Models/RegistroModel.cs
namespace SistemaAcademia.Models
{
    public class RegistroModel
    {
        public UsuarioModel Cadastro { get; set; }
        public LoginModel Entrada { get; set; }


      
    }
}

SistemaAcademia/Models/UsuarioModel.cs
using SistemaAcademia.Enums;
using System.ComponentModel.DataAnnotations;

namespace SistemaAcademia.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do usuário")]
        public string Nome { get; set; }
        
        [Required(ErrorMessage = "Digite o CPF ou CNPJ do usuário")]
        [RegularExpression(@"^[0-9-/.]+$", ErrorMessage = "Use apenas números")]
        public string CPFCNPJ { get; set; }

        [Required(ErrorMessage = "Digite o e-mail do usuário")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido")]
        public string Email { get; set; }

        [Required(ErrorMessage ="Digite o celular do usuário")]
        [Phone(ErrorMessage = "Informe um número válido")]
        public string Celular { get; set; }
        
        [Required(ErrorMessage = "Digite o login do usuário")]
        [RegularExpression(@"^[a-zA-Z0-9_.]+$", ErrorMessage = "Utilize apenas caracteres a-z, 0-1, '.' e '_' ")]
        public string Login { get; set; }
        
        [Required(ErrorMessage = "Digite o tipo de perfil do usuário")]
        public PerfilEnum? Perfil { get; set; }
        
        [Required(ErrorMessage = "Digite a senha do usuário")]
        public string Senha { get; set; }
        
        [Required(ErrorMessage = "Informe a data de nascimento do usuário")]
        [DisplayFormat(DataFormatString = "mm/dd/yyyy")]
        public DateTime DataNascimento { get; set; }

        public bool SenhaValida(string senha)
        {
            if (Senha == senha)
            {
                return true;
            }
            return false;
        }
    }
}

SistemaAcademia/Controllers/AcademiaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaAcademia.Controllers
{
    public class AcademiaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SistemaAcademia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaAcademia.Models;
using System.Diagnostics;

namespace SistemaAcademia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaAcademia/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaAcademia.Models;
using SistemaAcademia.Repositorio.Interfaces;

namespace SistemaAcademia.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public LoginController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(RegistroModel registroModel)
        {
            UsuarioModel usuario = registroModel.Cadastro;

            if (_usuarioRepositorio.VerifiqueRegistro(usuario))
            {



                _usuarioRepositorio.Adicionar(usuario);


                return RedirectToAction("Index");
            }
            return View("Index", registroModel);
        }


        [HttpPost]
        public IActionResult Entrar(RegistroModel registroModel)
        {
            LoginModel loginModel = registroModel.Entrada;
            if (_usuarioRepositorio.VerifiqueLogin(loginModel))
            {

                UsuarioModel usuario = _usuarioRepositorio.BuscarPorLogin(loginModel.Login);
                if(usuario.SenhaValida(loginModel.Senha))
                return RedirectToAction("Index", "Home");
            }
            return View("Index", registroModel);
        }
    }
}

SistemaAcademia/Views/Academia/Index.cshtml
@{
    ViewData["Title"] = "Registro de Acadamia";
}
<div class="text-center">
    <h2>Registrar Academia</h2>
    <br />
</div>

<form class="row g-3">
    

    <hr />

    <div class="col-md-3">
        <label for="inputZip" class="form-label">CEP</label>
        <input type="text" class="form-control" >

    </div>

    <div class="col-md-3">
        <label for="inputState" class="form-label">State</label>
        <select id="inputState" class="form-select">
            <option selected>Choose...</option>
            <option>...</option>
        </select>
    </div>

    <div class="col-3">
        <label for="inputAddress" class="form-label">Cidade</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-3">
        <label for="inputAddress" class="form-label">Bairro</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-6">
        <label for="inputAddress" class="form-label">Logradouro</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-2">
        <label for="inputAddress" class="form-label">Número</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-4">
        <label for="inputAddress" class="form-label">Complemento</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>

    <div class="col-12">
        <label for="inputAddress" class="form-label">Nome da academia</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>

    <div class="col-4">
        <label for="inputAddress" class="form-label">Login de acesso</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">E-mail</label>
        <input type="email" class="form-control" id="inputEmail4">
    </div>
    <div class="col-md-4">
        <label for="inputPassword4" class="form-label">Senha</label>
        <input type="password" class="form-control" id="inputPassword4">
    </div>

    <div class="col-12">
    </div>
    <div class="col-12 d-grid gap-2">
        <button type="submit" class="btn btn-primary">Registrar</button>
        <a class="btn btn-secondary">Voltar</a>
    </div>
</form>
<br />

SistemaAcademia/Views/Home/Index.cshtml
@model SistemaAcademia.Models.UsuarioModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo</h1>

    <img src="~/img/logo.png" alt="Bootstrap" width="290" height="254"  />
    
</div>

SistemaAcademia/Views/Login/Index.cshtml
@using SistemaAcademia.Enums;
@model RegistroModel

@{
    ViewData["Title"] = "Acesso do Usuário";
    Layout = "_LayoutDeslogado";
}
<div class="d-flex justify-content-center">
    <div class="form">

        <div class="buttons">
            <label for="chbox" class="login btn"><span>Login</span></label>
            <label for="chbox" class="Registro btn"><span>Registrar-se</span></label>
        </div>

        <input type="checkbox" id="chbox">
        <div class="layer"></div>
        <div class="layer2"></div>
        <div class="login_form">
            <form class="form-login" asp-controller="Login" asp-action="Entrar">
                <div class="mb-3">
                    <label asp-for="Entrada.Login" class="form-label">Login</label>
                    <input asp-for="Entrada.Login" type="text" class="form-control">
                    @Html.ValidationMessageFor(x => x.Entrada.Login)
                </div>
                <div class="mb-3">
                    <label asp-for="Entrada.Senha" class="form-label">Senha</label>
                    <input type="password" asp-for="Entrada.Senha" class="form-control">
                    @Html.ValidationMessageFor(x => x.Entrada.Senha)
                </div>
                <p class="mb-4 text-sm mx-auto">
                    Esqueceu sua senha?
                    <a href="#" class="fw-bold">Redefinir Senha</a>
                </p>
                <div class="col-12 d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Entrar</button>
                </div>
            </form>

        </div>

        <div class="Registro_form">
            <form class="form-registro" asp-controller="Login" asp-action="Criar" method="post">
                <div class="mb-3">
                    <label asp-for="Cadastro.Nome" class="form-label">Nome Completo</label>
                    <input type="text" asp-for="Cadastro.Nome" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.Nome)
                </div>
                <div class="mb-3">
                    <label asp-for="Cadastro.CPFCNPJ" class="form-label">CPF ou CNPJ</label>
                    <input type="text" asp-for="Cadastro.CPFCNPJ" id="cpfCnpj" onkeyup="formataValorCpfCnpj(this)" onpaste="TrataPaste(this, event, 'cpfCnpj')" maxlength=17 class="form-control">

                    @Html.ValidationMessageFor(x => x.Cadastro.CPFCNPJ)
                </div>
                <div class="mb-3">
                    <label asp-for="Cadastro.DataNascimento" class="form-label">Data de nascimento</label>
                    <input type="date" asp-for="Cadastro.DataNascimento" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.DataNascimento)
                </div>
                <div class="mb-3">
                    <label asp-for="Cadastro.Email" class="form-label">E-mail</label>
                    <input type="email" asp-for="Cadastro.Email" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.Email)
                </div>
                <div class="mb-3">
                    <label asp-for="Cadastro.Celular" class="form-label">Celular</label>
                    <input type="tel" asp-for="Cadastro.Celular" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.Celular)
                </div>


                <div class="mb-3">
                    <label asp-for="Cadastro.Login" class="form-label">Login</label>
                    <input type="text" asp-for="Cadastro.Login" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.Login)
                </div>
                <div class="mb-3">
                    <label for="PerfilEnum" class="form-label">Tipo de conta</label>
                    <select class="form-select" asp-for="Cadastro.Perfil">
                        <option selected>Selecione</option>
                        <option value="@PerfilEnum.Padrao">Aluno</option>
                        <option value="@PerfilEnum.Admin">Proprietário</option>
                    </select>
                    @Html.ValidationMessageFor(x => x.Cadastro.Perfil)
                </div>
                <div class="mb-3">
                    <label asp-for="Cadastro.Senha" class="form-label">Senha</label>
                    <input type="password" asp-for="Cadastro.Senha" class="form-control">
                    @Html.ValidationMessageFor(x => x.Cadastro.Senha)
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox">
                    <label class="form-check-label" for="termosCondicoes"></label>
                    Li e concordo com os <a href="#">Termos de Uso</a>
                </div>
                <div class="col-12 d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

SistemaAcademia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaAcademia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaAcademia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-4">
            <div class="container-fluid">
                <a class="navbar-brand d-inline-block align-text-top" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="imagemMC" src="~/img/logo.png" alt="Bootstrap" width="60" height="54" />

                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 nav justify-content-lg-start">

                        <li class="nav-item">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="vr"></li>
                        <li class="nav-item">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="vr"></li>
                        <li class="nav-item">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Academia" asp-action="Index">Academia</a>
                        </li>
                    </ul>

                    <div class="nav-item btn btn-outline-danger d-grid gap-2">
                        Sair
                    </div>





                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaAcademia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaAcademia/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaAcademia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-darkly.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaAcademia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-4">
            <div class="container-fluid">
                <a class="navbar-brand d-inline-block align-text-top" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="imagemMC" src="~/img/logo.png" alt="Bootstrap" width="60" height="54" />

                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 nav justify-content-lg-start">
                        
                    </ul>

                    <div class="nav-item  d-grid gap-2">
                        <a class="btn btn-outline-success text-dark" asp-controller="Login" asp-action="Index">
                            Login/Registrar
                        </a>
                    </div>





                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaAcademia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>